WebApplication1/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        PM_BanLinhKienPCEntities _db = new PM_BanLinhKienPCEntities();
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create( Customer cus)
        {
            _db.Customers.Add(cus);
            _db.SaveChanges();
            return RedirectToAction("ShowToCart", "ShoppingCart");
        }
    }
}

WebApplication1/Controllers/LinhKiensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class LinhKiensController : Controller
    {
        private PM_BanLinhKienPCEntities db = new PM_BanLinhKienPCEntities();

        // GET: LinhKiens
        public ActionResult Index()
        {
            return View(db.LinhKiens.ToList());
        }

        // GET: LinhKiens/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinhKien linhKien = db.LinhKiens.Find(id);
            if (linhKien == null)
            {
                return HttpNotFound();
            }
            return View(linhKien);
        }

        // GET: LinhKiens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LinhKiens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLK,MaLLK,MaNCC,TenLK,BaoHanh,XuatXu,TinhTrang,DonViTinh,DonGia,SoLuongTon,KhuyenMai,HinhAnh,TrangThai")] LinhKien linhKien)
        {
            if (ModelState.IsValid)
            {
                db.LinhKiens.Add(linhKien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(linhKien);
        }

        // GET: LinhKiens/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinhKien linhKien = db.LinhKiens.Find(id);
            if (linhKien == null)
            {
                return HttpNotFound();
            }
            return View(linhKien);
        }

        // POST: LinhKiens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLK,MaLLK,MaNCC,TenLK,BaoHanh,XuatXu,TinhTrang,DonViTinh,DonGia,SoLuongTon,KhuyenMai,HinhAnh,TrangThai")] LinhKien linhKien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(linhKien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(linhKien);
        }

        // GET: LinhKiens/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LinhKien linhKien = db.LinhKiens.Find(id);
            if (linhKien == null)
            {
                return HttpNotFound();
            }
            return View(linhKien);
        }

        // POST: LinhKiens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            LinhKien linhKien = db.LinhKiens.Find(id);
            db.LinhKiens.Remove(linhKien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        PM_BanLinhKienPCEntities _db = new PM_BanLinhKienPCEntities();
        public Cart GetCart()
        {
            Cart cart = Session["Cart"] as Cart;
            if (cart==null || Session["Cart"] == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
        // add item vao gio hang
        public ActionResult AddtoCart(String id)
        {
            var pro = _db.LinhKiens.SingleOrDefault(s => s.MaLK == id);
            if(pro != null)
            {
                GetCart().Add(pro);
            }
            return RedirectToAction("ShowToCart", "ShoppingCart");
        }
        //trang gio hang
        public ActionResult ShowToCart()
        {
            if(Session["Cart"] == null)
            {
                return RedirectToAction("ShowToCart", "ShoppingCart");
            }
            Cart cart = Session["Cart"] as Cart;
            return View(cart);
        }
        public ActionResult Update_Quantity_Cart(FormCollection form)
        {
            Cart cart = Session["Cart"] as Cart;
            String id_pro = form["ID_Product"];
            int quantity = int.Parse(form["Quantity"]);
            cart.Update_Quantity_Shopping(id_pro, quantity);
            return RedirectToAction("ShowToCart", "ShoppingCart");
        }
        public ActionResult RemoveCart(String id)
        {
            Cart cart = Session["Cart"] as Cart;
            cart.Remove_CartItem(id);
            return RedirectToAction("ShowToCart", "ShoppingCart");
        }
        public ActionResult BagCart()
        {
            int _t_item = 0;
            Cart cart = Session["Cart"] as Cart;
            if (cart != null)
            {
                _t_item = cart.Total_Quantity();

            }
            ViewBag.infoCart = _t_item;
            return PartialView("BagCart");
        }
        public ActionResult Shopping_Success ()
        {
            return View();
        }

        // Thanh Toan      
        public ActionResult CheckOut(FormCollection form)
        {
            try
            {
                Cart cart = Session["Cart"] as Cart;
                Order _order = new Order();                            
                _order.OrderDate = DateTime.Now;
                _order.CodeCus = int.Parse(form["CodeCustomer"]);
                _order.Descriptions = form["Address_Delivery"];
                _db.Orders.Add(_order);
                foreach(var item in cart.Items)
                {
                    OrderDetail _other_Detail = new OrderDetail();
                    _other_Detail.IDOrder = _order.IDOrder;
                    _other_Detail.MaLK = item._shopping_product.MaLK;
                    _other_Detail.UnitPriceSale = item._shopping_product.DonGia;
                    _other_Detail.Quantity = item._shopping_quantity;
                    _db.OrderDetails.Add(_other_Detail);
                }
                _db.SaveChanges();
                cart.ClearCart();
                return RedirectToAction("Shopping_Success", "ShoppingCart");
            }
            catch
            {
                return Content("Error Checkout. Vui lòng kiểm tra lại....");
            }
        }
    }
}

WebApplication1/Views/ShoppingCart/BagCart.cshtml
@model WebApplication1.Models.Cart
<span class="badge" style="color:white; margin-left: 10px; text-align:center"; >@ViewBag.infoCart</span>

WebApplication1/Views/ShoppingCart/Shopping_Success.cshtml
@{
    ViewBag.Title = "Shopping_Success";
}



<body style="text-align: center">
    <h2>Shopping Successful</h2>
    <h4>Đơn hàng của bạn đã được xác nhận. Đơn hàng sẽ được chuyển đến bạn trong 2-3 ngày. Hẹn gặp lại !!!</h4>
    <a class ="btn btn-success" href="@Url.Action("Index","LinhKiens")">Tiếp tục mua sắm ....</a>
</body>

WebApplication1/Views/ShoppingCart/ShowToCart.cshtml
@model WebApplication1.Models.Cart
    

@{
    ViewBag.Title = "ShowToCart";
}

<h2>ShowToCart</h2>
@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Image</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Sum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                double total = Convert.ToDouble(item._shopping_product.DonGia.Value * item._shopping_quantity);
                <tr>
                    <td>
                        @Html.DisplayFor(model => item._shopping_product.TenLK)
                    </td>
                    <td>
                        <img src="@Url.Content(item._shopping_product.HinhAnh)" style="width: 100px; height: 100px;" />
                    </td>
                    <td>
                        @Html.DisplayFor(model => item._shopping_product.DonGia)
                    </td>
                    <td>
                        @using (Html.BeginForm("Update_Quantity_Cart", "ShoppingCart"))
                        {
                            <input type="hidden" value=" @item._shopping_product.MaLK" name="ID_Product" />
                            <input type="number" value="@item._shopping_quantity" name="Quantity" />
                            <input type="submit" value="Update Quantity" />
                        }
                    </td>
                    <td>
                        Total: @total
                    </td>
                    <td>
                        <a href="/ShoppingCart/RemoveCart/@item._shopping_product.MaLK">Remove</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2"></td>
                <td colspan="4" style="text-align:left;">
                    @using (Html.BeginForm("CheckOut", "ShoppingCart"))
                    {
                        <table style="border-collapse:separate; border-spacing: 5px;">
                            <tr>
                                <td>Code Customer</td>
                                <td>
                                    <input type="number" name="CodeCustomer" required />
                                </td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>
                                    Address Delivery:
                                </td>
                                <td>
                                    <input type="text" name="Address_Delivery" required />
                                </td>
                                <td></td>
                            </tr>
                            <tr>
                                <td>
                                    <a href="@Url.Action("Create","Customers")" class="btn btn-success">Register</a>
                                </td>
                                <td>
                                    <input type="submit" value="Checkout" class="btn btn-success" />
                                </td>
                                <td></td>
                            </tr>
                        </table>
                    }

                </td>               
            </tr>
            <tr>
                <td colspan="5" style="text-align: right">Sum Total: @Model.ToTal_Money() </td>
            </tr>
        </tfoot>


    </table>
    <a href="@Url.Action("Index","LinhKiens")">Continue to shopping</a>
}